final-8.13

diff --git a/aesd-char-driver/aesdchar_load b/aesd-char-driver/aesdchar_load
--- a/aesd-char-driver/aesdchar_load
+++ b/aesd-char-driver/aesdchar_load
@@ -2,8 +2,8 @@
 module=aesdchar
 device=aesdchar
 mode="664"
-echo "Loading aesdchar module - datoteka"
-
+cd `dirname $0`
+set -e
 # Group: since distributions do it differently, look for wheel or use staff
 if grep -q '^staff:' /etc/group; then
     group="staff"
@@ -11,10 +11,13 @@ else
     group="wheel"
 fi
 
-
-echo "Loading local built file ${module}"
-modprobe $module $* || exit 1
-
+if [ -e ${module}.ko ]; then
+    echo "Loading local built file ${module}.ko"
+    insmod ./$module.ko $* || exit 1
+else
+    echo "Local file ${module}.ko not found, attempting to modprobe"
+    modprobe ${module} || exit 1
+fi
 major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
 rm -f /dev/${device}
 mknod /dev/${device} c $major 0
